### ISSUE TITLE
chiarimento su richiedente

### ISSUE THREAD

**Issue by PietroLodiRizzini** [AlexZorzi/PassaportoBot#1]
il readme dice di inserire un richiedente, ma nel video non mi pare di vedere richiedenti inseriti.
Con un richiedente inserito il sito mi chiede per quale persona voglio prenotare e il bot sceglie la prima tra le proposte, che sono io e non il richiedente che ho inserito.
Come potrei fare per selezionare una persona diversa?
E' possibile avere chiarimenti su questo aspetto?

grazie

**Comment by AlexZorzi** [comment]
dovrebbe essere risolto in [#bba01a32a01a32](https://github.com/AlexZorzi/PassaportoBot/commit/ba01a32ba49d547abdb632e3f9ffbc0eac0456cf) inserisci il nome preciso del richiedente. fammi sapere se funziona

**Comment by PietroLodiRizzini** [comment]
risolto, grazie
